# Generated by Django 2.1.4 on 2020-02-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200222_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_entrada', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='platodefondo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_platodefondo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='refresco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_refresco', models.CharField(max_length=12)),
            ],
        ),
    ]
