# Generated by Django 2.1.4 on 2020-02-22 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_registroestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_menu', models.DateField(blank=True, default=datetime.date.today)),
                ('id_entrada_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_entrada', to='menu.entrada')),
                ('id_entrada_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_entrada_2', to='menu.entrada')),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_operador', to='menu.operador')),
                ('id_platodefondo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_platodefondo', to='menu.entrada')),
                ('id_platodefondo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_platodefondo_2', to='menu.entrada')),
                ('id_refreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_refresco', to='menu.entrada')),
            ],
        ),
    ]
