# Generated by Django 2.1.4 on 2020-02-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id_platodefondo_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_platodefondo', to='menu.platodefondo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id_platodefondo_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_platodefondo_2', to='menu.platodefondo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id_refreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_refresco', to='menu.refresco'),
        ),
    ]
