# Generated by Django 2.1.4 on 2020-02-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200222_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='id_refreso',
            new_name='id_refresco',
        ),
        migrations.AlterField(
            model_name='registroestado',
            name='descripcion_registroestado',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
