# Generated by Django 2.1.4 on 2020-02-22 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200222_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(blank=True, default=datetime.date.today)),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_menu', to='menu.entrada')),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_operador', to='menu.operador')),
                ('id_registroestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_registroestado', to='menu.registroestado')),
            ],
        ),
    ]
