# Generated by Django 2.1.4 on 2020-02-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200222_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_menu', to='menu.menu'),
        ),
    ]
