# Generated by Django 2.1.4 on 2020-02-23 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menu_descripcion_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidoatendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atendido', models.DateField(blank=True, default=datetime.date.today)),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoatendido_operador', to='menu.operador')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoatendido_pedido', to='menu.pedido')),
                ('id_registroestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidoatendido_registroestado', to='menu.registroestado')),
            ],
        ),
    ]
